baseURL = 'https://alecks131.github.io/'
languageCode = 'en'
title = 'Under a Glassy Sky'
theme = 'coder'

[params]
    author = "Aleksei"
    description = "Physics Student & Developer"
    keywords = "blog,developer,personal,physics"
    info = "Physics Student & Tech Enthusiast"
    avatarURL = "images/avatar.jpg" # Place your photo in static/images/avatar.jpg
    footerContent = "Built with Hugo & Coder"
    
    # Enable Math (LaTeX) Support
    math = true

[[menu.main]]
    name = "About"
    weight = 1
    url = "about/"

[[menu.main]]
    name = "Posts"
    weight = 2
    url = "posts/"