baseURL = 'https://alecks131.github.io/'
languageCode = 'en-us'
title = 'Under a Glassy Sky'
theme = 'loficode'

[params]
    math = true
    [params.author]
        name = "Aleksei"
        image = "avatar.jpg"
        bio = "Physics and Math Student"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 20
